site_name: eQual framework
site_url: https://doc.equal.run/
repo_name: equal
repo_url: https://github.com/equalframework/equal
edit_uri: ""
docs_dir: docs
theme:
  name: material
  favicon: '_assets/img/favicon.png'
  logo: '_assets/img/eq_logo.png'
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
  # 404 page
  static_templates:
    - 404.html
extra_css:
  - '_assets/css/extra.css'
plugins:
  - search
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.details
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
nav: